export const ALERT_TITLES = {
  success: {
    saved: "Saved",
    updated: "Updated",
    sent: "Sent",
    checkInbox: "Check your inbox",
    continueOnWeb: "Continue on web",
    draftReady: "Draft ready",
  },
  info: {
    emailRequired: "Email required",
    checkDetails: "Check details",
    actionNotAllowed: "Action not allowed",
    microphoneAccessNeeded: "Microphone access needed",
    whatsappUnavailable: "WhatsApp unavailable",
  },
  confirm: {
    deletion: "Confirm deletion",
  },
  error: {
    unableToSignIn: "Unable to sign in",
    unableToCreateAccount: "Unable to create account",
    unableToSaveProfile: "Unable to save profile",
    unableToLoadCustomer: "Unable to load customer",
    unableToLoadOrders: "Unable to load orders",
    unableToUpdateOrder: "Unable to update order",
    unableToAssignDelivery: "Unable to assign delivery",
    unableToCreatePaymentLink: "Unable to create payment link",
    unableToUpdateLoyalty: "Unable to update loyalty",
    unableToSaveProduct: "Unable to save product",
    unableToSaveSettings: "Unable to save settings",
    unableToSendInvite: "Unable to send invite",
    unableToStartUpgrade: "Unable to start upgrade",
    unableToSendResetLink: "Unable to send reset link",
    unableToSaveCustomer: "Unable to save customer",
    unableToExportAnalytics: "Unable to export analytics",
    unableToSendCampaign: "Unable to send campaign",
    unableToStartRecording: "Unable to start recording",
    unableToAccessRecording: "Unable to access recording",
    unableToParseVoiceNote: "Unable to parse voice note",
    unableToLoadCampaignHistory: "Unable to load campaign history",
    unableToLoadInventory: "Unable to load inventory",
    unableToUpdateStock: "Unable to update stock",
    unableToLoadLoyalty: "Unable to load loyalty",
    unableToSaveLoyaltyRules: "Unable to save loyalty rules",
    unableToLoadMarketplace: "Unable to load marketplace",
  },
} as const;
